#ifndef COSTANT_H_
#define COSTANT_H_

#define SN 4
#define NUMBER_OF_EMPLOYED 2
#define NUMBER_OF_ONLOOKER SN-NUMBER_OF_EMPLOYED
#define D 3
#define LIMIT 3
#define MAX_CYCLES 1000

#define SPHERE 1
#define ROSENBROCK 2
#define ACKLEY 3
#define GRIEWANK 4
#define WEIERSTRASS 5
#define RASTRIGIN 6
#define NON_CONTINUOUS_RASTRIGIN 7
#define SCHWEFEL 8

#define FUNCTION SCHWEFEL

#endif